In [1]:
%load_ext autoreload
%autoreload 2

import os
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

import numpy as np
from strategy_v2.Strategy import *
from strategy_v2.Strategy.MVO import *
from strategy_v2.Strategy.MVO.AlphaModel import *
from strategy_v2.Strategy.MVO.RiskModel import *
from strategy_v2.TradingSubSystem import *
from strategy_v2.Portfolio import *
from strategy_v2.TransactionCost import *
from strategy_v2.Executor import *
from utils.data_helper import *
from utils.data import *
from utils.performance import *
from utils.ta import *

In [2]:
instruments = [
    'META',
    'TSLA',
    'NVDA',
    'AAPL',        
    'BRK-B',
    'SPY',
    'QQQ',
    'NANC',    
    'CASH',    
]
end_date = get_today(0)
start_date = pd.to_datetime(datetime(2024, 1, 3))
# start_date = pd.to_datetime(datetime(2023, 2, 7))
max_leverage = 1
#vol_target = 0.25
vol_target = None
end_date

Timestamp('2025-12-05 00:00:00')

# Notes

- 2024-08-28: Tested expected return prediction with RandomForest, XGB, LGBM. None of them outperforms the SMA Model. LGBM is able to achieve a similar performance as SMA model and generally train faster.</br>

    | Measure                | ^SPX      | MVO - SMA1 | MVO - RandomForest1 | MVO - XGB1 | MVO - LGBM1 |
    |------------------------|-----------|------------|---------------------|------------|-------------|
    | Cumulative Return      | 1.173503  | 2.072994   | 1.662573            | 1.471717   | 2.023378    |
    | Annualized Return      | 0.076775  | 0.301537   | 0.221185            | 0.176047   | 0.296252    |
    | Annualized Volatility  | 0.180081  | 0.226417   | 0.240133            | 0.243953   | 0.243120    |
    | Annualized Sharpe Ratio| 0.240438  | 1.183923   | 0.781685            | 0.584416   | 1.080844    |
    | Maximum Drawdown       | -0.254251 | -0.271732  | -0.323658           | -0.380737  | -0.296535   |

    Models are shared the same hyperparameters: lookback (train days) = 10 days and gamma=10, hhi=0.2

## Leverage 
##### 1. capital (Stock MV / last leverage), 2. new leverage
2024-09-06: $169,336, 96.69%

2024-09-20: $172,168, 93.52%

2024-10-04: $176,235, 100%

2024-10-18: $177,831, 100%

2024-11-01: $175,558, 100%

2024-11-09: $181,511

2024-11-22: $187,224

2024-11-30: $188,332

2024-12-06: $194,828

2024-12-13: $211,354, CASH: $3778

2024-12-20: $198,713, CASH: $38,024 (+$20000 Capital)

2025-01-04: $192,246, CASH: $23,606

2024-01-10: $205,516, CASH: $18,562

2025-01-17: $213,405, CASH: $18,835

2025-01-24: $216,851, CASH: $11,204

2025-01-31: $228,709, CASH: $4,254

2025-02-07: $232,687, CASH: $9,159

2025-02-14: $230,291, CASH: $5,880

2025-02-21: $232,495, CASH: $5,202

2025-02-28: $214,062, CASH: $32,893

2025-03-07: $183,794, CASH: $44,484

2025-03-14: $170,198, CASH: $61,726

2025-03-21: $157,754, CASH: $21,438

2025-03-28: $194,943, CASH: $26,857

2025-04-04: $169,914, CASH: $56,364

2025-04-11: $110,474, CASH: $55,374

2025-04-26: $115,939, CASH: $31,518

2025-05-09: $141,999, CASH: $28,033

2025-05-23: $149,548, CASH: $28,489

2025-06-06: $159,449, CASH: ??

2025-06-20: $158,981, CASH: $38,573

2025-07-12: $159,517, CASH: $2,484

2025-07-26: $201,144, CASH: $2,553

2025-08-23: $211,523, CASH: -$3,500

2025-09-24: $228,235, CASH: -$7,421

2025-10-25: $239,447, CASH: 14,219

2025-12-29: $221,437, CASH: 35,466

# Log

2024-11-22: If we don't fix sum of weights to constant (e.g. 1), the model would statisfy the HHI constraints by reducing the overeall weights only, but not diversing the portfolios. Still, fixing to 1 is not good because sometime we should de-leverage given signals are weak. So we can consider to add a cash element in the optimization

2024-11-30: Create benchmark portfolios (e.g. equally weighted of all stocks) (DONE)

2024-12-06: Alpha models using returns relative to something (e.g. SPX)

In [4]:
portfolio = PortfolioStandard(
    capital=221437 + 35466,
    name='MVOPortfolio',        
    rebalance_iter=RebalancerIter('0 0 * * Fri', 1),        
    tc_model=TransactionCostFutu(), 
    systems_style=SystemStyle.VERTICAL,
    systems=[        
        # Long terms signals => 60days return / diversified        
        TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=RollingMean(60), risk_model=RollingMeanCovNeg(60), gamma=10, hhi=0.2, confidence=1, leverage=1)], max_leverage=max_leverage, offset=60),

        # Mid terms signals => 30days return / diversified        
        TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=RollingMean(30), risk_model=RollingMeanCovNeg(30), gamma=10, hhi=0.2, confidence=0.5, leverage=1)], max_leverage=max_leverage, offset=60),

        # Short terms signals => 5 and 10days returns / less diversified
        TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=RollingMean(20), risk_model=RollingMeanCovNeg(20), gamma=30, hhi=0.4, confidence=0.5, leverage=1)], max_leverage=max_leverage, offset=60),         
        # TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=RollingMean(5), risk_model=RollingMeanCovNeg(5), gamma=30, hhi=0.4, confidence=0.5, leverage=1)], max_leverage=max_leverage, offset=60),         

        # Mean Revert signals => 2days RSI / concentrated
        # TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=RSI(2,10), risk_model=ZeroCov(), gamma=0, hhi=0, confidence=0.2)], max_leverage=max_leverage, offset=200),
        # TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=RSI(2,95), risk_model=ZeroCov(), gamma=0, hhi=0, confidence=-1)], max_leverage=max_leverage, offset=200),

        # Mean Revert signals => Double7 / concentrated
        TradingSubSystemSingle(vol_target=vol_target, instruments=instruments, strategy=[MeanVarianceOpt(alpha_model=Double7(5), risk_model=ZeroCov(), gamma=0, hhi=0, confidence=0.2)], max_leverage=max_leverage, offset=200),
    ]
)

portfolio.set_start_date(start_date)
portfolio.set_end_date(end_date)
portfolio.backtest_subsystems()
portfolio.optimize()
portfolio.backtest()
portfolio.rebalance()
portfolio.performance(show_all_rets=True)

[*********************100%***********************]  8 of 8 completed
2025-11-29 03:53:03,982 - TradingSubSystemSingle [MVO - RollingMean(60)|1] - INFO - Generating position for strategy MVO - RollingMean(60)|1 between 2024-01-02 and 2025-11-28......
 97%|█████████▋| 486/499 [00:03<00:00, 155.37it/s]2025-11-29 03:53:07,544 - MeanVarianceOpt - INFO - 2025-11-28 is today, shift position date to include latest market data at 03:11 AM
100%|██████████| 499/499 [00:03<00:00, 142.72it/s]
2025-11-29 03:53:07,562 - TradingSubSystemSingle [MVO - RollingMean(60)|1] - INFO - Volatility Target = nan% | Price Volatility = 22.0% | Last Scale Factor = 1.00
2025-11-29 03:53:07,565 - TradingSubSystemSingle [MVO - RollingMean(30)|0.5] - INFO - Generating position for strategy MVO - RollingMean(30)|0.5 between 2024-01-02 and 2025-11-28......
 98%|█████████▊| 489/499 [00:03<00:00, 156.17it/s]2025-11-29 03:53:10,824 - MeanVarianceOpt - INFO - 2025-11-28 is today, shift position date to include latest market data at 03:11 AM
100%|██████████| 499/499 [00:03<00:00, 153.06it/s]
2025-11-29 03:53:10,846 - TradingSubSystemSingle [MVO - RollingMean(30)|0.5] - INFO - Volatility Target = nan% | Price Volatility = 8.5% | Last Scale Factor = 1.00
2025-11-29 03:53:10,858 - TradingSubSystemSingle [MVO - RollingMean(20)|0.5] - INFO - Generating position for strategy MVO - RollingMean(20)|0.5 between 2024-01-02 and 2025-11-28......
 98%|█████████▊| 487/499 [00:03<00:00, 158.49it/s]2025-11-29 03:53:14,176 - MeanVarianceOpt - INFO - 2025-11-28 is today, shift position date to include latest market data at 03:11 AM
100%|██████████| 499/499 [00:03<00:00, 150.42it/s]
2025-11-29 03:53:14,191 - TradingSubSystemSingle [MVO - RollingMean(20)|0.5] - INFO - Volatility Target = nan% | Price Volatility = 6.3% | Last Scale Factor = 1.00
[*********************100%***********************]  8 of 8 completed
2025-11-29 03:53:14,822 - TradingSubSystemSingle [MVO - Double(5)|0.2] - INFO - Generating position for strategy MVO - Double(5)|0.2 between 2024-01-02 and 2025-11-28......
 94%|█████████▍| 471/499 [00:01<00:00, 286.14it/s]2025-11-29 03:53:16,862 - MeanVarianceOpt - INFO - 2025-11-28 is today, shift position date to include latest market data at 03:11 AM
100%|██████████| 499/499 [00:01<00:00, 279.33it/s]
2025-11-29 03:53:16,873 - TradingSubSystemSingle [MVO - Double(5)|0.2] - INFO - Volatility Target = nan% | Price Volatility = 8.1% | Last Scale Factor = 1.00
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  9 of 9 completed
[*********************100%***********************]  1 of 1 completed

,Rebalanced Portfolio,Optimized Portfolio,^SPX,Equal Weighted,MVO - RollingMean(60)|1,MVO - RollingMean(30)|0.5,MVO - RollingMean(20)|0.5,MVO - Double(5)|0.2
Measure,,,,,,,,
Cumulative Return,2.183407,2.067535,1.455763,1.853884,2.003154,1.453907,1.677279,1.146555
Annualized Return,0.438003,0.411723,0.210710,0.350648,0.395410,0.203848,0.280258,0.075839
Annualized Volatility,0.231934,0.242153,0.162038,0.227534,0.243703,0.117346,0.126770,0.088312
Annualized Sharpe Ratio,1.780407,1.596747,1.145686,1.430918,1.519659,1.523555,2.013037,0.574937
Maximum Drawdown,-0.211875,-0.214293,-0.189022,-0.228358,-0.219302,-0.103090,-0.083024,-0.094187

In [5]:
portfolio.portfolio_breakdown()
portfolio.instrument_breakdown()

In [6]:
portfolio.get_position_for_trade().tail(20)

2025-11-29 03:53:31,357 - Standard Portfolio ({self.name}) - CRITICAL - Portfolio target capital is not specified, use initial backtest capital of $256,903
2025-11-29 03:53:31,357 - Standard Portfolio ({self.name}) - INFO - Generate trade position based on target capital of $256,903

             AAPL  BRK-B  META   NANC   NVDA   QQQ   SPY   TSLA     CASH
Date
2025-10-31  292.0   15.0   4.0  376.0  202.0  32.0  24.0   99.0  30043.0
2025-11-03  292.0   15.0   4.0  376.0  202.0  32.0  24.0   99.0  30043.0
2025-11-04  292.0   15.0   4.0  376.0  202.0  32.0  24.0   99.0  30043.0
2025-11-05  292.0   15.0   4.0  376.0  202.0  32.0  24.0   99.0  30043.0
2025-11-06  292.0   15.0   4.0  376.0  202.0  32.0  24.0   99.0  30043.0
2025-11-07  293.0   36.0   0.0  356.0  204.0  21.0  17.0  109.0  32522.0
2025-11-10  293.0   36.0   0.0  356.0  204.0  21.0  17.0  109.0  32522.0
2025-11-11  293.0   36.0   0.0  356.0  204.0  21.0  17.0  109.0  32522.0
2025-11-12  293.0   36.0   0.0  356.0  204.0  21.0  17.0  109.0  32522.0
2025-11-13  293.0   36.0   0.0  356.0  204.0  21.0  17.0  109.0  32522.0
2025-11-14  323.0   85.0   0.0  346.0   76.0  25.0  24.0  130.0  11729.0
2025-11-17  323.0   85.0   0.0  346.0   76.0  25.0  24.0  130.0  11729.0
2025-11-18  323.0   85.0   0.0  346.0   76.0  25.0  24.0  130.0  11729.0
2025-11-19  323.0   85.0   0.0  346.0   76.0  25.0  24.0  130.0  11729.0
2025-11-20  323.0   85.0   0.0  346.0   76.0  25.0  24.0  130.0  11729.0
2025-11-21  315.0  103.0   0.0  265.0   39.0  21.0  22.0  120.0  28020.0
2025-11-24  315.0  103.0   0.0  265.0   39.0  21.0  22.0  120.0  28020.0
2025-11-25  315.0  103.0   0.0  265.0   39.0  21.0  22.0  120.0  28020.0
2025-11-26  315.0  103.0   0.0  265.0   39.0  21.0  22.0  120.0  28020.0
2025-11-28  237.0  105.0   0.0  350.0  145.0  30.0  33.0   90.0  15875.0

# Execute the Portfolio

In [ ]:
executor = ExecutorFutu(is_test=False)
executor.set_portfolio(portfolio)
orders = executor.execute(px_interval='5m')
orders

2025-11-29 03:55:43,490 - ExecutorFutu - INFO - market: US
2025-11-29 03:55:43,491 - ExecutorFutu - INFO - Cancel all orders first before executing.....

2025-11-29 03:55:43,494 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=19, host=127.0.0.1, port=11111, user_id=18214795
2025-11-29 03:55:44,403 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=20, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:55:46,627 - Standard Portfolio ({self.name}) - CRITICAL - Portfolio target capital is not specified, use initial backtest capital of $256,903
2025-11-29 03:55:46,627 - Standard Portfolio ({self.name}) - INFO - Generate trade position based on target capital of $256,903
2025-11-29 03:55:46,636 - ExecutorFutu - INFO - Execute Standard Portfolio ({self.name}) position based on 2025-11-28

2025-11-29 03:55:46,638 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=21, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:55:46,670 - Futu - INFO - 7 Positions: US.TSLA, US.SPY, US.QQQ, US.NVDA, US.NANC, US.BRK.B, US.AAPL

  instrument  target  current  turnover
0       AAPL   237.0    184.0      53.0
1      BRK-B   105.0     18.0      87.0
2       META     0.0      0.0       0.0
3       NANC   350.0    517.0    -167.0
4       NVDA   145.0    179.0     -34.0
5        QQQ    30.0     68.0     -38.0
6        SPY    33.0     23.0      10.0
7       TSLA    90.0    111.0     -21.0

[*********************100%***********************]  8 of 8 completed
2025-11-29 03:55:47,218 - ExecutorFutu - INFO - getting last 5m prices since 2025-11-28 17:55:00 for order limit price

2025-11-29 03:55:47,221 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=22, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:55:47,527 - Futu - INFO - Placed Order: {'code': 'US.AAPL', 'price': 278.52, 'qty': 53.0, 'trd_side': 'BUY', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

2025-11-29 03:55:50,540 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=23, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:55:50,828 - Futu - INFO - Placed Order: {'code': 'US.BRK.B', 'price': 515.08, 'qty': 87.0, 'trd_side': 'BUY', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

2025-11-29 03:55:53,835 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=24, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:55:54,139 - Futu - INFO - Placed Order: {'code': 'US.NANC', 'price': 45.91, 'qty': 167.0, 'trd_side': 'SELL', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

2025-11-29 03:55:57,142 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=25, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:55:57,414 - Futu - INFO - Placed Order: {'code': 'US.NVDA', 'price': 177.0, 'qty': 34.0, 'trd_side': 'SELL', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

2025-11-29 03:56:00,426 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=26, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:56:00,728 - Futu - INFO - Placed Order: {'code': 'US.QQQ', 'price': 619.24, 'qty': 38.0, 'trd_side': 'SELL', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

2025-11-29 03:56:03,740 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=27, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:56:04,036 - Futu - INFO - Placed Order: {'code': 'US.SPY', 'price': 681.88, 'qty': 10.0, 'trd_side': 'BUY', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

2025-11-29 03:56:07,042 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=28, host=127.0.0.1, port=11111, user_id=18214795

2025-11-29 03:56:07,303 - Futu - INFO - Placed Order: {'code': 'US.TSLA', 'price': 430.25, 'qty': 21.0, 'trd_side': 'SELL', 'order_type': 'NORMAL', 'market': 'US', 'trd_env': 'REAL'}

,code,stock_name,trd_side,order_type,order_status,order_id,qty,price,create_time,updated_time,...,remark,time_in_force,fill_outside_rth,aux_price,trail_type,trail_value,trail_spread,currency,portfolio,date
0,US.AAPL,苹果,BUY,NORMAL,SUBMITTING,FH1BADDF0CDEFF2000,53.0,278.52,2025-11-28 14:55:47,2025-11-28 14:55:47,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28
0,US.BRK.B,伯克希尔-B,BUY,NORMAL,SUBMITTING,FH1BADDF1019EE8000,87.0,515.08,2025-11-28 14:55:50,2025-11-28 14:55:50,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28
0,US.NANC,UNUSUAL WHALES SUBVERSIVE DEMOCRATIC TRADING ETF,SELL,NORMAL,SUBMITTING,FH1BADDF13533F2000,167.0,45.91,2025-11-28 14:55:54,2025-11-28 14:55:54,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28
0,US.NVDA,英伟达,SELL,NORMAL,SUBMITTING,FH1BADDF1689648000,34.0,177.00,2025-11-28 14:55:57,2025-11-28 14:55:57,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28
0,US.QQQ,纳指100ETF-Invesco QQQ Trust,SELL,NORMAL,SUBMITTING,FH1BADDF19C7DFA000,38.0,619.24,2025-11-28 14:56:00,2025-11-28 14:56:00,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28
0,US.SPY,标普500ETF-SPDR,BUY,NORMAL,SUBMITTING,FH1BADDF1D001FA000,10.0,681.88,2025-11-28 14:56:04,2025-11-28 14:56:04,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28
0,US.TSLA,特斯拉,SELL,NORMAL,SUBMITTING,FH1BADDF20356E8000,21.0,430.25,2025-11-28 14:56:07,2025-11-28 14:56:07,...,Standard Portfolio ({self.name}),DAY,False,N/A,N/A,N/A,N/A,USD,Standard Portfolio ({self.name}),2025-11-28

2025-11-29 04:13:56,435 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=29, host=127.0.0.1, port=11111, user_id=18214795
2025-11-30 03:41:30,943 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=30, host=127.0.0.1, port=11111, user_id=18214795
2025-11-30 15:00:58,693 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=31, host=127.0.0.1, port=11111, user_id=18214795
2025-12-01 03:03:35,732 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=32, host=127.0.0.1, port=11111, user_id=18214795
2025-12-01 05:44:07,116 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=33, host=127.0.0.1, port=11111, user_id=18214795
2025-12-01 15:08:42,911 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=34, host=127.0.0.1, port=11111, user_id=18214795
2025-12-02 00:54:50,825 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=35, host=127.0.0.1, port=11111, user_id=18214795
2025-12-03 02:08:49,117 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=36, host=127.0.0.1, port=11111, user_id=18214795
2025-12-03 09:54:58,898 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=37, host=127.0.0.1, port=11111, user_id=18214795
2025-12-04 07:11:13,347 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=38, host=127.0.0.1, port=11111, user_id=18214795
2025-12-05 22:19:08,489 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=39, host=127.0.0.1, port=11111, user_id=18214795
2025-12-06 01:06:02,570 | 7617 | [open_context_base.py] _send_init_connect_sync:311: InitConnect ok: conn_id=40, host=127.0.0.1, port=11111, user_id=18214795